__author__ = "LabSid PHA EPUSP"
__email__ = "rubem.hydrological@labsid.eng.br"
__copyright__ = "Copyright 2020-2022, LabSid PHA EPUSP"
__license__ = "GPL"
__date__ = "2022-03-23"
__version__ = "0.1.3"
__release__ = __version__ + "-alpha"
