"""Generator of a minimal synthetic 3x3 dataset for in-process model tests.

The dataset is physically plausible (values mirror one land-use and one soil
class of the regression fixtures) but tiny, so a full model run takes
milliseconds. It exists for behavior tests; the regression oracle remains the
fixture dataset under ``tests/fixtures/base``.
"""

import os
from datetime import date

import numpy as np

ROWS = 3
COLS = 3
CELL_SIZE = 500.0
WEST = 0.0
NORTH = 1500.0
MISSING = -9999.0

_LULC_CLASSES = (3, 4)
_SOIL_CLASS = 1

_DATE_FORMAT = "%d/%m/%Y"
_START_DATE = date(2000, 1, 1)
# The input series repeat every ``_SERIES_CYCLE`` steps, which keeps NDVI inside the
# declared min/max rasters and rainfall positive for any number of steps.
_SERIES_CYCLE = 6

# Two land-use classes that alternate over the series, so that a test can tell a
# land-use raster from another one: with a single class every step would look the
# same and any fallback would produce identical outputs. The area fractions of a
# class add up to 1.
_LULC_TABLES = {
    "a_i": {3: 0.0, 4: 0.1},
    "a_o": {3: 0.0, 4: 0.0},
    "a_s": {3: 0.0, 4: 0.3},
    "a_v": {3: 1.0, 4: 0.6},
    "manning": {3: 0.16, 4: 0.05},
    "kcmin": {3: 1.14, 4: 0.85},
    "kcmax": {3: 1.8, 4: 1.25},
}
_SOIL_TABLES = {
    "dg": 1.54,
    "Kr": 38.29,
    "Tcc": 0.26,
    "Tsat": 0.46,
    "Tw": 0.12,
    "Zr": 150.39,
}
ROOTZONE_DEPTH = _SOIL_TABLES["Zr"]
"""Rootzone depth (``Zr``) of the soil class [cm]."""


def _as_tif(path):
    return os.path.splitext(path)[0] + ".tif"


def _write_geotiff(path, array, scale, pcr):
    """Write ``array`` as a GeoTIFF on the synthetic geometry (no CRS)."""
    from osgeo import gdal

    gdal.UseExceptions()
    gdal.AllRegister()
    if scale is pcr.Scalar:
        gdal_type, nodata, data = gdal.GDT_Float32, MISSING, np.asarray(array, dtype=np.float32)
    elif scale is pcr.Boolean:
        gdal_type, nodata, data = gdal.GDT_Byte, 255, np.asarray(array, dtype=np.uint8)
    else:
        gdal_type, nodata, data = gdal.GDT_Int32, int(MISSING), np.asarray(array, dtype=np.int32)
    dataset = gdal.GetDriverByName("GTiff").Create(path, COLS, ROWS, 1, gdal_type)
    try:
        band = dataset.GetRasterBand(1)
        band.SetNoDataValue(float(nodata))
        band.WriteArray(data)
        dataset.SetGeoTransform((WEST, CELL_SIZE, 0.0, NORTH, 0.0, -CELL_SIZE))
        dataset.FlushCache()
    finally:
        dataset = None


def geotiff_series_name(prefix, step):
    """File name of a GeoTIFF series member, as the model writes its outputs."""
    return f"{prefix}{str(step).zfill(10 - len(prefix))}.tif"


def series_name(prefix, step):
    """Return the PCRaster map-series name of ``prefix`` at ``step``.

    PCRaster keeps series names in the 8.3 form and pushes the digits that no
    longer fit the three-character extension into the stem (step 1000 of
    ``ndvi`` is ``ndvi0001.000``), so the name is generated by PCRaster itself
    instead of being formatted here.
    """
    from pcraster.framework import generateNameT

    return generateNameT(prefix, step)


def _end_date(timesteps):
    """Return the last simulated month, rolling across calendar years."""
    months = _START_DATE.month - 1 + (timesteps - 1)
    return date(_START_DATE.year + months // 12, months % 12 + 1, _START_DATE.day)


def write_synthetic_dataset(base_dir, timesteps=2, raster_format="map"):
    """Write the dataset under ``base_dir`` and return its configuration dict.

    :param base_dir: Directory that receives ``maps/``, ``txt/`` and ``out/``.
    :param timesteps: Number of monthly steps starting at 01/01/2000. Must be at
        least 2, since :class:`SimulationPeriod` requires the start date to
        precede the end date.
    :param raster_format: ``"map"`` writes PCRaster maps (the default), ``"tif"``
        writes every raster and series member as a GeoTIFF (series members named
        like the model outputs, ``<prefix><step>.tif``).
    :raises ValueError: If ``timesteps`` is smaller than 2.
    """
    import pcraster as pcr

    if raster_format not in ("map", "tif"):
        raise ValueError(f"raster_format must be 'map' or 'tif', got {raster_format!r}.")
    suffix = raster_format

    if timesteps < 2:
        raise ValueError(
            f"timesteps must be at least 2, got {timesteps}: a simulation period needs"
            " a start date that precedes its end date."
        )

    base_dir = str(base_dir)
    pcr.setclone(ROWS, COLS, CELL_SIZE, WEST, NORTH)

    def write_map(rel_path, values, scale, dtype):
        path = os.path.join(base_dir, "maps", rel_path)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        array = np.asarray(values, dtype=dtype).reshape(ROWS, COLS)
        if suffix == "tif":
            path = _as_tif(path)
            _write_geotiff(path, array, scale, pcr)
            return path
        pcr.report(pcr.numpy2pcr(scale, array, MISSING), path)
        return path

    dem = np.linspace(100.0, 140.0, ROWS * COLS)
    write_map("dem/dem.map", dem, pcr.Scalar, np.float32)
    write_map("clone/clone.map", np.ones(ROWS * COLS), pcr.Boolean, np.uint8)
    ldd_field = pcr.lddcreate(
        pcr.numpy2pcr(pcr.Scalar, dem.reshape(ROWS, COLS).astype(np.float32), MISSING),
        1e31,
        1e31,
        1e31,
        1e31,
    )
    ldd_path = os.path.join(base_dir, "maps", "ldd", "ldd.map")
    os.makedirs(os.path.dirname(ldd_path), exist_ok=True)
    if suffix == "tif":
        ldd_path = _as_tif(ldd_path)
        _write_geotiff(ldd_path, pcr.pcr2numpy(ldd_field, 0).astype(np.int32), pcr.Nominal, pcr)
    else:
        pcr.report(ldd_field, ldd_path)
    write_map("soil/soil.map", np.full(ROWS * COLS, _SOIL_CLASS), pcr.Nominal, np.int32)
    samples = np.full(ROWS * COLS, MISSING)
    samples[0] = 1
    samples[ROWS * COLS - 1] = 2
    write_map("samples/samples.map", samples, pcr.Nominal, np.float64)
    write_map("ndvi/ndvi_min.map", np.full(ROWS * COLS, 0.2), pcr.Scalar, np.float32)
    write_map("ndvi/ndvi_max.map", np.full(ROWS * COLS, 0.9), pcr.Scalar, np.float32)

    def member(prefix, step):
        return geotiff_series_name(prefix, step) if suffix == "tif" else series_name(prefix, step)

    for step in range(1, timesteps + 1):
        cycle = (step - 1) % _SERIES_CYCLE + 1
        write_map(
            f"ndvi/{member('ndvi', step)}",
            np.full(ROWS * COLS, 0.5 + 0.05 * cycle),
            pcr.Scalar,
            np.float32,
        )
        write_map(
            f"etp/{member('etp', step)}",
            np.full(ROWS * COLS, 80.0 + 5.0 * cycle),
            pcr.Scalar,
            np.float32,
        )
        write_map(
            f"rain/{member('prec', step)}",
            np.full(ROWS * COLS, 120.0 - 10.0 * cycle),
            pcr.Scalar,
            np.float32,
        )
        write_map(
            f"kp/{member('kp', step)}",
            np.full(ROWS * COLS, 0.8),
            pcr.Scalar,
            np.float32,
        )
        write_map(
            f"lulc/{member('cob', step)}",
            np.full(ROWS * COLS, _LULC_CLASSES[(step - 1) % len(_LULC_CLASSES)]),
            pcr.Nominal,
            np.int32,
        )

    txt_dir = os.path.join(base_dir, "txt")
    os.makedirs(os.path.join(txt_dir, "lulc"), exist_ok=True)
    os.makedirs(os.path.join(txt_dir, "soil"), exist_ok=True)
    for name, values in _LULC_TABLES.items():
        with open(os.path.join(txt_dir, "lulc", f"{name}.txt"), "w", encoding="utf8") as f:
            for lulc_class in _LULC_CLASSES:
                f.write(f"{lulc_class} {values[lulc_class]}\n")
    for name, value in _SOIL_TABLES.items():
        with open(os.path.join(txt_dir, "soil", f"{name}.txt"), "w", encoding="utf8") as f:
            f.write(f"{_SOIL_CLASS} {value}\n")
    with open(os.path.join(txt_dir, "rainydays.txt"), "w", encoding="utf8") as f:
        for month in range(1, 13):
            f.write(f"{month}\t{10 + month % 3}\n")

    output_dir = os.path.join(base_dir, "out")
    os.makedirs(output_dir, exist_ok=True)
    maps = os.path.join(base_dir, "maps")
    return {
        "SIM_TIME": {
            "start": _START_DATE.strftime(_DATE_FORMAT),
            "end": _end_date(timesteps).strftime(_DATE_FORMAT),
        },
        "DIRECTORIES": {
            "output": output_dir,
            "etp": os.path.join(maps, "etp/"),
            "prec": os.path.join(maps, "rain/"),
            "ndvi": os.path.join(maps, "ndvi/"),
            "kp": os.path.join(maps, "kp/"),
            "landuse": os.path.join(maps, "lulc/"),
        },
        "FILENAME_PREFIXES": {
            "etp_prefix": "etp",
            "prec_prefix": "prec",
            "ndvi_prefix": "ndvi",
            "kp_prefix": "kp",
            "landuse_prefix": "cob",
        },
        "RASTERS": {
            "dem": os.path.join(maps, f"dem/dem.{suffix}"),
            "clone": os.path.join(maps, f"clone/clone.{suffix}"),
            "ldd": os.path.join(maps, f"ldd/ldd.{suffix}"),
            "ndvi_max": os.path.join(maps, f"ndvi/ndvi_max.{suffix}"),
            "ndvi_min": os.path.join(maps, f"ndvi/ndvi_min.{suffix}"),
            "soil": os.path.join(maps, f"soil/soil.{suffix}"),
            "samples": os.path.join(maps, f"samples/samples.{suffix}"),
        },
        "TABLES": {
            "rainydays": os.path.join(txt_dir, "rainydays.txt"),
            "a_i": os.path.join(txt_dir, "lulc/a_i.txt"),
            "a_o": os.path.join(txt_dir, "lulc/a_o.txt"),
            "a_s": os.path.join(txt_dir, "lulc/a_s.txt"),
            "a_v": os.path.join(txt_dir, "lulc/a_v.txt"),
            "manning": os.path.join(txt_dir, "lulc/manning.txt"),
            "bulk_density": os.path.join(txt_dir, "soil/dg.txt"),
            "k_sat": os.path.join(txt_dir, "soil/Kr.txt"),
            "t_fcap": os.path.join(txt_dir, "soil/Tcc.txt"),
            "t_sat": os.path.join(txt_dir, "soil/Tsat.txt"),
            "t_wp": os.path.join(txt_dir, "soil/Tw.txt"),
            "rootzone_depth": os.path.join(txt_dir, "soil/Zr.txt"),
            "k_c_min": os.path.join(txt_dir, "lulc/kcmin.txt"),
            "k_c_max": os.path.join(txt_dir, "lulc/kcmax.txt"),
        },
        "GRID": {"grid": CELL_SIZE},
        "CALIBRATION": {
            "alpha": 4.5,
            "b": 0.5,
            "w_1": 0.333,
            "w_2": 0.333,
            "w_3": 0.334,
            "rcd": 5.0,
            "f": 0.5,
            "alpha_gw": 0.5,
            "x": 0.5,
        },
        "INITIAL_SOIL_CONDITIONS": {
            "t_ini": 1.0,
            "bfw_ini": 0.1,
            "bfw_lim": 1.0,
            "s_sat_ini": 1.1,
        },
        "CONSTANTS": {
            "fpar_max": 0.95,
            "fpar_min": 0.001,
            "lai_max": 12.0,
            "i_imp": 2.5,
        },
        "GENERATE_FILE": {
            "itp": True,
            "bfw": True,
            "srn": True,
            "eta": True,
            "lfw": True,
            "rec": True,
            "smc": True,
            "rnf": True,
            "arn": True,
            "tss": True,
        },
        "RASTER_FILE_FORMAT": {"map_raster_series": True, "tiff_raster_series": True},
    }


def write_lai_max_table(config, values=None):
    """Write a ``lai_max`` lookup table next to the land use tables and return its path.

    The table is not part of the configuration returned by
    :func:`write_synthetic_dataset`; a test sets ``TABLES.lai_max`` and
    ``CONSTANTS.lai_max_from_table`` itself.

    :param config: The configuration returned by :func:`write_synthetic_dataset`.
    :param values: ``{land use class: LAI_max}``; by default a distinct value per class.
    """
    if values is None:
        values = {3: 9.0, 4: 4.0}
    path = os.path.join(os.path.dirname(config["TABLES"]["a_v"]), "lai_max.txt")
    with open(path, "w", encoding="utf8") as f:
        for lulc_class, value in values.items():
            f.write(f"{lulc_class} {value}\n")
    return path


MODFLOW_TOP = 100.0
MODFLOW_LAYER_THICKNESS = 20.0
MODFLOW_HEAD = 90.0
MODFLOW_KH_TABLE = {1: 0.5, 2: 0.1}


def write_grid_map(path, values, nominal=False):
    """Write ``values`` (nine numbers, row by row) as a PCRaster map on the synthetic grid.

    :param path: The map file; its directory is created.
    :param values: A scalar broadcast to the grid, or ``ROWS * COLS`` values;
        ``NaN`` and :data:`MISSING` cells are missing.
    :param nominal: Whether the map is nominal (classes) instead of scalar.
    :returns: ``path`` as a string.
    """
    import pcraster as pcr

    pcr.setclone(ROWS, COLS, CELL_SIZE, WEST, NORTH)
    array = np.broadcast_to(np.asarray(values, dtype=np.float64), (ROWS * COLS,))
    array = np.where(np.isnan(array), MISSING, array).reshape(ROWS, COLS)
    os.makedirs(os.path.dirname(str(path)), exist_ok=True)
    if nominal:
        field = pcr.numpy2pcr(pcr.Nominal, array.astype(np.int32), int(MISSING))
    else:
        field = pcr.numpy2pcr(pcr.Scalar, array.astype(np.float32), MISSING)
    pcr.report(field, str(path))
    return str(path)


def write_modflow_inputs(config, layers=3):
    """Write the inputs of a MODFLOW section on the synthetic grid and return the section.

    The layers are listed top down under a flat model top at
    :data:`MODFLOW_TOP`, each :data:`MODFLOW_LAYER_THICKNESS` thick and active
    everywhere, with the initial head :data:`MODFLOW_HEAD` in every layer.
    Layer 1 is unconfined (LAYCON 1) with its horizontal conductivity given by
    classes (row 1 class 1, the other rows class 2, see
    :data:`MODFLOW_KH_TABLE`) and its vertical conductivity by a map; the other
    layers are convertible (LAYCON 2) with a conductivity map and a number. The
    river lies on the middle column of layer 1 (numeric conductance and a
    mask), the general head boundary on the left column of every layer, the
    drain package is off and wetting applies to layer 1.

    :param config: The configuration returned by :func:`write_synthetic_dataset`;
        the files go to ``maps/modflow`` next to its rasters.
    :param layers: Number of layers.
    :returns: The ``MODFLOW`` section, with absolute paths.
    """
    maps = os.path.dirname(os.path.dirname(config["RASTERS"]["clone"]))
    directory = os.path.join(maps, "modflow")

    def grid(name, values, nominal=False):
        return write_grid_map(os.path.join(directory, name), values, nominal)

    left_column = [1.0 if index % COLS == 0 else 0.0 for index in range(ROWS * COLS)]
    middle_column = [1.0 if index % COLS == 1 else 0.0 for index in range(ROWS * COLS)]
    table = os.path.join(directory, "kh1.tbl")
    os.makedirs(directory, exist_ok=True)
    with open(table, "w", encoding="utf8") as f:
        for kh_class, value in MODFLOW_KH_TABLE.items():
            f.write(f"{kh_class} {value}\n")
    boundary = grid("bound.map", 1, nominal=True)
    head = grid("head.map", MODFLOW_HEAD)
    section_layers = []
    for number in range(1, layers + 1):
        item = {
            "name": f"layer{number}",
            "bottom": grid(f"bottom{number}.map", MODFLOW_TOP - number * MODFLOW_LAYER_THICKNESS),
            "initial_head": head,
            "boundary": boundary,
            "laytype": 2,
            "horizontal_conductivity": grid("kh.map", 1.0),
            "vertical_conductivity": 0.1,
            "specific_yield": 0.15,
            "specific_storage": 1e-5,
        }
        if number == 1:
            classes = [1] * COLS + [2] * (ROWS - 1) * COLS
            item["laytype"] = 1
            item["horizontal_conductivity"] = {
                "map": grid("kh_classes1.map", classes, nominal=True),
                "table": table,
            }
            item["vertical_conductivity"] = grid("kv1.map", 0.1)
        section_layers.append(item)
    return {
        "enabled": True,
        "top": grid("top.map", MODFLOW_TOP),
        "layers": section_layers,
        "wetting": {"enabled": True, "map": grid("wet.map", 1.0), "layers": [1]},
        "river": {
            "enabled": True,
            "entries": [
                {
                    "layers": [1],
                    "stage": grid("riv_stage.map", MODFLOW_HEAD + 5.0),
                    "bottom": grid("riv_bottom.map", MODFLOW_TOP - 10.0),
                    "conductance": 10.0,
                    "mask": grid("riv_mask.map", middle_column),
                }
            ],
        },
        "ghb": {
            "enabled": True,
            "entries": [
                {
                    "layers": list(range(1, layers + 1)),
                    "head": grid("ghb_head.map", MODFLOW_HEAD),
                    "conductance": grid("ghb_cond.map", left_column),
                }
            ],
        },
        "drain": {"enabled": False, "entries": []},
    }


def write_minimum_root_depth_table(config, value):
    """Write a ``Dpz_min`` lookup table next to the soil tables and return its path.

    :param config: The configuration returned by :func:`write_synthetic_dataset`.
    :param value: Minimum root depth of the soil class, in the unit of ``Zr`` [cm].
    """
    path = os.path.join(os.path.dirname(config["TABLES"]["rootzone_depth"]), "Dpz_min.txt")
    with open(path, "w", encoding="utf8") as f:
        f.write(f"{_SOIL_CLASS} {value}\n")
    return path
