name: Build Release
on:
    push:
      branches: "!*"
      tags: "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: rubem-ci
        environment-file: env-ci.yml
        python-version: 3.10
        auto-activate-base: false

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

    - name: Create Version File
      run: |
        echo "${{ steps.get_version.outputs.VERSION }}".substring(1) + ".0" > version.txt
        create-version-file metadata.yml --outfile versionfile.txt
    
    - name: Create Package
      run: pyinstaller rubem.spec --noconfirm

    - name: Test Package
      run: |
        ./dist/rubem/rubem -h

    - name: Zip files
      run: |
        7z a -tzip -mx=9 -r "dist\rubem-v${{ steps.get_version.outputs.VERSION }}-win-x86_64.zip" dist\rubem\*

    - name: Test Zip
      run: |
        7z t "dist/rubem-v${{ steps.get_version.outputs.VERSION }}-win-x86_64.zip"

    - name: Compute Hash
      run: |
        $hash = Get-FileHash -Path dist/rubem-v${{ steps.get_version.outputs.VERSION }}-win-x86_64.zip -Algorithm SHA512
        echo $hash.Hash $([System.IO.Path]::GetFileName($hash.Path)) > dist/rubem-v${{ steps.get_version.outputs.VERSION }}-win-x86_64.zip.sha512

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        name: v${{ steps.get_version.outputs.VERSION }}
        files: |
          ./dist/rubem-v${{ steps.get_version.outputs.VERSION }}-win-x86_64.zip
          ./dist/rubem-v${{ steps.get_version.outputs.VERSION }}-win-x86_64.zip.sha512
        draft: false
        prerelease: false
